// @kyra/shared - Shared types and validations
export {
	// Auth
	USER_ROLES,
	type UserRole,
	type User,
	type AuthUser,
	type Invite,
	setupSchema,
	loginSchema,
	createInviteSchema,
	acceptInviteSchema,
	updateUserSchema_auth,
	updateProfileSchema,
	transferOwnershipSchema,
	type SetupInput,
	type LoginInput,
	type CreateInviteInput,
	type AcceptInviteInput,
	type UpdateUserAuthInput,
	type UpdateProfileInput,
	type TransferOwnershipInput,
	canManageUsers,
	canManageDatabases,
	canEditContent,
	canManageRole,
	canTransferOwnership,
	getInitials,
	// Domain
	VIEW_TYPES,
	type ViewType,
	FIELD_TYPES,
	type FieldType,
	type KanbanStatusOption,
	LOOKUP_OPERATORS,
	type LookupOperator,
	type LookupFilter,
	type LookupSettings,
	type Database,
	type Field,
	type Record,
	type Page,
	type Block,
	type BlockWithRelations,
	type PageWithBlocks,
	createDatabaseSchema,
	updateDatabaseSchema,
	reorderDatabasesSchema,
	type CreateDatabaseInput,
	type UpdateDatabaseInput,
	type ReorderDatabasesInput,
	fieldTypeSchema,
	createFieldSchema,
	bulkCreateFieldsSchema,
	updateFieldSchema,
	reorderFieldsSchema,
	type CreateFieldInput,
	type BulkCreateFieldsInput,
	type UpdateFieldInput,
	type ReorderFieldsInput,
	createRecordSchema,
	updateRecordSchema,
	type CreateRecordInput,
	type UpdateRecordInput,
	viewTypeSchema,
	createPageSchema,
	updatePageSchema,
	reorderPagesSchema,
	type CreatePageInput,
	type UpdatePageInput,
	type ReorderPagesInput,
	createBlockSchema,
	updateBlockSchema,
	reorderBlocksSchema,
	type CreateBlockInput,
	type UpdateBlockInput,
	type ReorderBlocksInput,
	buildRecordValidator,
	toSlug,
	resolveRecordSlugs,
	// Comments
	type Comment,
	type CommentWithAuthor,
	createCommentSchema,
	type CreateCommentInput,
	// Notifications
	type Notification,
	type NotificationWithActor,
	// API Keys
	type ApiKey,
	createApiKeySchema,
	type CreateApiKeyInput,
	// Webhooks
	type Webhook,
	createWebhookSchema,
	updateWebhookSchema,
	type CreateWebhookInput,
	type UpdateWebhookInput,
	// Customers
	type Customer,
	type CustomerContact,
	type CustomerWithContacts,
	createCustomerSchema,
	updateCustomerSchema,
	createContactSchema,
	type CreateCustomerInput,
	type UpdateCustomerInput,
	type CreateContactInput,
	// Invoices
	INVOICE_STATUSES,
	type InvoiceStatus,
	NFSE_STATUSES,
	type NfseStatus,
	type Invoice,
	type InvoiceWithCustomer,
	updateInvoiceSchema,
	syncInvoicesSchema,
	issueNfseSchema,
	type UpdateInvoiceInput,
	type SyncInvoicesInput,
	type IssueNfseInput,
	// Billings
	type Billing,
	type BillingWithCustomer,
	// Company Settings
	FOCUS_NFE_ENVIRONMENTS,
	type FocusNfeEnvironment,
	type CompanySettings,
	upsertCompanySettingsSchema,
	type UpsertCompanySettingsInput,
	// Administrative
	canManageAdministration,
} from "./types";
